### ISSUE TITLE
xml.monkey doesn't require #XML_USE_LOADSTRING

### ISSUE THREAD

**Issue by philippeback** [swoolcock/diddy#52]
The new Desktop_Game_(Glfw3) target doesn't require that to be set.

' only import os or mojo if LoadString is enabled
'#If XML_USE_LOADSTRING
	' import os if LoadString is implemented there, otherwise import mojo
'	#If TARGET="stdcpp" Or TARGET="glfw" Or TARGET="Desktop Game (Glfw3)"
'		Import os
'	#Else
		Import mojo
'	#End
'#End

Method ParseFile:XMLDocument(filename:String)
'#If Not XML_USE_LOADSTRING_DISABLED
'		Throw New UnsupportedOperationException("ParseFile has been temporarily disabled due to LoadString() on HTML5 and other targets requiring Mojo to be imported.  To continue using it, set #XML_USE_LOADSTRING=True")
'#Else
		Print "ParseFile " + filename

I guess it would be sufficient to do that only for stdcpp

Now works.

**Comment by philippeback** [comment]
I am using MonkeyXPro85e with MinGW

**Comment by swoolcock** [comment]
I assume your pull request fixes this.
