### ISSUE TITLE
BaseTween.userData private?

### ISSUE THREAD

**Issue by ratkingsminion** [swoolcock/diddy#57]
With the new Tween stuff I can set user data to a tween via Tween.TweenTo(...).UserData(myData), but eg. in the OnEvent() callback of TweenCallback, where I have a BaseTween parameter, I cannot read the userData field because it is private. Is that an oversight, or did I something wrong? IMHO it can just be an public field.

**Comment by therevills** [comment]
I've added a property getter to BaseTween for userdata. Let me know if this works for you and then I'll close this issue.

**Comment by ratkingsminion** [comment]
That should do it! All I do is casting the userData of the source BaseTween to my own object where I put all the necessary data.

**Comment by therevills** [comment]
Good to hear :+1:
